"""add patients tb

Revision ID: 445874610919
Revises: 3f2621281f4a
Create Date: 2023-04-14 17:46:45.071302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '445874610919'
down_revision = '3f2621281f4a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('gender', sa.Boolean(), nullable=False),
    sa.Column('tel', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('insurance_number', sa.String(), nullable=False),
    sa.Column('surgery_history', sa.String(), nullable=False),
    sa.Column('allergy', sa.String(), nullable=False),
    sa.Column('drug_history', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('pid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patients')
    # ### end Alembic commands ###
