"""add a pwd field to employees and patients field

Revision ID: 545f4c5bbd4b
Revises: f6957d339a25
Create Date: 2023-04-14 18:22:07.459607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '545f4c5bbd4b'
down_revision = 'f6957d339a25'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('pwd', sa.String(), nullable=False))
    op.add_column('patients', sa.Column('pwd', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'pwd')
    op.drop_column('employees', 'pwd')
    # ### end Alembic commands ###
