"""employees tb fk role_id set to cascade

Revision ID: 70ef7712c857
Revises: 445874610919
Create Date: 2023-04-14 17:59:30.554732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70ef7712c857'
down_revision = '445874610919'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('employees_role_id_fkey', 'employees', type_='foreignkey')
    op.create_foreign_key(None, 'employees', 'roles', ['role_id'], ['rid'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.create_foreign_key('employees_role_id_fkey', 'employees', 'roles', ['role_id'], ['rid'], ondelete='SET DEFAULT')
    # ### end Alembic commands ###
